// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdamkKBMO2y9f0JvZvrY88xzu3WDuQWxA',
    appId: '1:996048124214:web:eb8bb63ea270d8a5eb9b97',
    messagingSenderId: '996048124214',
    projectId: 'tander-dating',
    authDomain: 'tander-dating.firebaseapp.com',
    storageBucket: 'tander-dating.appspot.com',
    measurementId: 'G-PPZ73ZKRMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwwcepPZ19J2u4Wg0XbMGOvZrt8sn3v90',
    appId: '1:996048124214:android:835bd9b509bdc2baeb9b97',
    messagingSenderId: '996048124214',
    projectId: 'tander-dating',
    storageBucket: 'tander-dating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOa0ApZAmcs9jaG4YzJE42VygKjKwpWOg',
    appId: '1:996048124214:ios:2dc3ab14db6d72a5eb9b97',
    messagingSenderId: '996048124214',
    projectId: 'tander-dating',
    storageBucket: 'tander-dating.appspot.com',
    iosClientId: '996048124214-t501mqrk6qiu2km2kdean3vp1s9dk0ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOa0ApZAmcs9jaG4YzJE42VygKjKwpWOg',
    appId: '1:996048124214:ios:9bf27057acf0d75eeb9b97',
    messagingSenderId: '996048124214',
    projectId: 'tander-dating',
    storageBucket: 'tander-dating.appspot.com',
    iosClientId: '996048124214-hqm5gp0ktrepc24a1fd3r911s31orfro.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingAppClone.RunnerTests',
  );
}
